#+title: 週報 2023/11/06 ~ 2023/11/12
#+date: 2023-11-12
#+tags[]: 週報
#+categories[]: 週報
#+draft: false

** 今週の動画

前回の予告と違う動画になってしまうけど、はんだづけのやり方の解説動画を見たので載せる。
わかりやすかったし、記事の本文にも書くけど自作キーボードを始めるのに参考になりそうだった。

#+HTML: <lite-youtube videoid="dQ7AUjb1tkA"></lite-youtube>

** [[https://zenn.dev/ytr0903/articles/c6c42147ed29be?utm_source=pocket_saves][UnJS にどんなツールがあるのか、上位30件すべて紹介してみた]]

Vue.js は今まで一度も使ったことがなかったので、どのライブラリも初めて知るものだった。
記事で紹介されているのは 30 だけだがスライドを見ると UnJS は 50 以上のライブラリ群からなるようだ。
いくつかのライブラリは業務で使うような簡単な CLI を作るときに使えそうなので、機会を見つけて実際に利用してみようと思う。

** [[https://qiita.com/Tsuyoshi84/items/e398ac4449a36286c0d7?utm_source=pocket_saves][console.log() の代わりにdevtoolsのLogpointsを使う #JavaScript - Qiita]]

普段雰囲気で Developer Tools を使っているので知らない機能がある。
今まで `console.log` を入れたり、ブレークポイントを張って値の中身を確認していたので、
特定の操作を一通り行ったときの値の変化を見たいときは Logpoints を使うのがよさそうだと思った。

** [[https://coliss.com/articles/build-websites/operation/css/magnetic-hover-effect-with-has-and-anchor-positioning.html?utm_source=pocket_saves][CSSのみで簡単に実装できる！ マグネットのようにくっついて追従するホバーエフェクトを実装するテクニック | コリス]]

CSS も毎年新しい機能が追加されているけどまったく追えてないことをコリスに投稿される記事を読んでると実感する。
どこかで CSS の機能もキャッチアップできるようにしていかないとなぁ…。

** 個人的なできごと

*** Osmo Pocket 3 が届いた

何週か前の週報に載せたけど Osmo Pocket 3 が 10 月末頃に発売した。
Vlog 撮らないけど気になったので買ってしまった。

夜でも明るく撮れる。
来週か、再来週に新宿御苑に紅葉でも見に行こうと思っているので、
その時に撮った動画を YouTube にアップロードしようかな。

*** Keyball61 を買った

ずっと前から気になっていた [[https://shirogane-lab.net/items/64b8ed191435c1002bc4cd30][Keyball61]] が入荷していたので注文した。
これはキーボードにトラックボールが内蔵しているキーボードだ。
自作キーボードはしたことがないので遊舎工房で自作キーボードのためのキットと入門書のようなものを買った。

- [[https://shop.yushakobo.jp/products/a0900kj-00-1?_pos=2&_sid=efbcec9b8&_ss=r][ここからはじめる自作キーボード]]
- [[https://shop.yushakobo.jp/products/a9900to?_pos=39&_sid=8e5b9c4bc&_ss=r][工具セット]]

ただ、フラックス洗浄剤が入ってなかった。
そのため、キムワイプと一緒にヨドバシ・ドット・コムで購入した。

** まとめ

来週から自作キーボードやっていくぞい。
