#+title: Rainy75 Pro
#+date: 2024-04-27
#+tags[]: キーボード
#+categories[]: キーボード
#+draft: false

** TL;DL

+ Rainy75 Pro を買った
+ 打鍵音はコトコトして心地いい
+ キーはスムーズで押下圧は軽い

** はじめに

3月頃に Makuake でクラウドファンディングをしていた [[https://www.makuake.com/project/rainy75/][Rainy 75 Pro]] が届いた。
今年に入ってから購入した 4 つ目のキーボードになる。

** Rainy75 Pro

Rainy75 は Makuake のタイトルにもあるように音を売りにしているキーボードだ。
まずは、YouTube の動画を聴いてみて欲しい。

#+HTML: <lite-youtube videoid="EH9S1AbF3aY"></lite-youtube>

なかなかにいい感じの音じゃないだろうか。

音のいいキーボードというのがどのようなものなのか気になったので、
これ以上キーボードを増やしても使いきれないことはわかりつつもファンディングしてしまった。
Rainy75 は Lite、Color、Pro 系の 3 タイプが用意されているが、それぞれの違いはそこまで調べず Pro 系モデルを選んだ。

あまり熟考せずに購入してしまったが、Lofree Flow の経験からしてクラファンではなく通常販売が開始してから購入した方が安くなるのではないだろうか :smile:
購入価格は 17% OFF で 24,900 円だった。

*** スペック表

アフィリエイトサイトではないので、キーボードのスペックは Makuake を確認して欲しい、が改めて比較をしたいため表にまとめてみる。

| 項目           | Lite 系            | Color 系                     | Pro 系                                      |
|----------------+--------------------+------------------------------+---------------------------------------------|
| *価格*          | 23,000 円          | 26,000 円                    | 30,000 円                                   |
| *色*             | 黒/シルバー         | シルバーR/ホワイト/ブルー/ピンク | ホワイトPro/ブルーPro/スペシャルパープ/ピンクPro |
| *ウェイトデザイン* | カラーガラス/ガラス  | カラーガラス/ガラスデザイン     | ステンレス                                   |
| *キースイッチ*    | 紫キースイッチ (HMX) | 紫キースイッチ (HMX)           | 黒白キースイッチ (JWK)                        |
| *バッテリー*      | 3,500 mah          | 3,500 mah                    | 7,000 mah                                   |
| *RGB*            | なし               | あり                         | あり                                        |

実際には Lite、Color については色によってウェイトデザインが異なり、それぞれの色に対してウェイトのデザインの組み合わせがあるわけではない。
これはどうにかならなかったのだろうか。

購入したのはスペシャルパープルなのでウェイトデザインはステンレス、キースイッチは黒白キースイッチ、バッテリーは 7,000 mah。

*** キースイッチ

キースイッチは HMX 社製の紫キースイッチ、JWK 社製の黒白キースイッチの二つがある。
いずれのスイッチもリニアで押下圧は 45 g、40 g。
個人的には押下圧は軽い方が好みなので結果として Pro 系を購入してよかった。

打鍵音はキースイッチだけではなく、ケースやパッド、フォーム、キーキャップの影響を受けるので、
キースイッチだけの恩恵ではないと思うが、スムーズで打ち心地がよく 40 g にして軽いように感じる。

今使っているキーボードは [[https://keychron.co.jp/products/kailh-deep-sea-silent-pro-box-switch?variant=42735721611435][Kailh Deep Sea Silent Pro Box スイッチ Linearlslet]] に変えてしまったが、
最近までは [[https://shop.yushakobo.jp/products/7998][Akko Silver Pro Switch]] を使っていた。
このキースイッチも同じく押下圧が 40g だが Rainy75 よりも重く感じる。
フォースカーブを見ると底に打つまでに必要な圧が Akko Silver Pro Switch の方が必要なのでその影響だろう。
これからキースイッチを買うときは、底打ち時の押下圧についても気をつけて見るようにしようと思った。

*** ケース

ケースにはアルミ合金を採用している。アルミケースは Lofree Flow 以外持っていないので届いてから重さに驚いた。
やはりノーマルプロファイルのケースともなると重たい。スペック表にも 1.8kg って書いてあった。
1.5L のペットボトルよりも重たい。とてもではないが持ち歩ける重さではないので自宅でメインで使っている PC のキーボードとして使うことにする。

*** 接続方法

接続方法は、有線 (Type-C)、無線 (2.4 GHz)、Bluethooth の 3 種類に対応している。
最近のキーボードは大体これらを備えているだろう。

しかし、一つ問題があるとすれば有線と無線、Bluethooth の切り替えをするために Caps Lock を外さなければならない。
この重さのキーボードを動かすことはないので滅多に外さないが、それでも購入初期は何度か有線で繋いだので少し面倒ではある。

** 感想

割引もあって価格は 25,000 円でこのビルドクオリティならば中々いい買い物だったのではないだろうか。
FPS での利用をメインに考えると最近流行りのラピッドトリガーに対応していないので候補から外れてしまうが、
FPS をしない人であれば日常使い、業務、ゲームでの利用を目的として購入するのはありではないだろうか。

唯一不満を上げるとすれば、色、キースイッチ、ウェイトデザインの組み合わせを自由にできるようにして欲しい。
スペシャルパープルにカラーガラスのウェイトを付けたバージョンが欲しかった…。

それでも 25,000 円という価格を考慮するとコスパはいいのではないかと思う。
この価格帯のノーマルプロファイルキーボードを買ったのは初めてなので、本当の価値がわかるようになるのはこれからだろう。
相対的な比較を何度かしないと物の価値を判断するのは難しい。
自作キーボードの価格に目が慣れてしまったため 25,000 円でこのビルドクオリティが手に入るであればコスパがいいという判断をしてしまう。
