#+title: leneko42C
#+date: 2024-03-21
#+tags[]: キーボード 自作キーボード
#+categories[]: キーボード
#+draft: false

** はじめに

2023 年度も残すところわずかで、この時期になると困ることの一つに有給休暇の消化がある。
体調不良や飛び石休日を連休にする以外で有給休暇を使わないので毎年余らせてしまっている。

そんなわけで今週は水曜日が祝日だったので残りの有給休暇の消費のために一週間まるまる休みを取った。
さて、引きこもりは1週間休みに何をするでしょうか。
そう、キーボードを組みます。

今回は [[https://booth.pm/ja/items/4790055][leneko42C]] を組みました。
流石にキーボードを組むのは 4 つ目なので慣れたもので組み立てではトラブルもなかった。
唯一あったトラブルとしては、秋葉原の秋月電子に PGA2040 を土曜日に買いに行ったら
営業時間が 19 時までで買うことができず、翌日にまた来るのも面倒なのでネット注文を使ったところ
配達されたのが水曜日になってしまい時間を損失してしまったことだろうか。
翌日くらいに発送されるかなーという気持ちでネット注文にしたけど、
これなら月曜日に秋葉原を通る用事があったので日を改めて店頭で買った方がよかったと少し後悔。

** 特徴

leneko42C の主な特徴は以下の通り。

+ 42キー
+ トラックパッド
+ カラムスタッガード配列
+ 非分割

何と言ってもトラックパッドが付いているのが一番の特徴だろう。
このキーボード以外にもトラックパッドを搭載した自作キーボードキットは存在するが、
それでもまだ数としては少ないので珍しいだろう。

** 構成

+ [[https://booth.pm/ja/items/4790055][leneko42C]]
+ [[https://shop.yushakobo.jp/products/5684?_pos=1&_sid=814f57ca5&_ss=r&_fid=984fd9fe5][Akko Herb Garden Keycap Set]]
+ [[https://www.fumo-shop.com/ducky-keyswitch-cherry-mx-silver.html][Cherry MX Speed Silver Switches Batch]]

キースイッチとキーキャップは余っているものを利用した。

** 使用感

組み立ててから最初に書いている文章がこのブログの記事なため、
文字通りファーストインプレッションとなってしまうが、
今のところ継続的に利用していこうと思っているくらいにはいい。

もともと布団の中に入っているときに使えるキーボードはないかなーと思って購入し、
まさにこの記事を布団の中で枕に顔を埋めながら書いているが、
多少の不自由はあるものの文章を書くくらいであれば問題なく使えそうなことがわかった。

現在感じている不自由は主に 2 点ある。
一つはキー数が 42 個しかないことに起因する難しさで、
もう一つが macOS で利用したときのトラックパッドの挙動だ。

キーが 42 個しかないため、この手のキーボードではレイヤーを活用していかなければならない。
メインのレイヤーで入力できる文字はアルファベットと一部の記号だけになっている。
数字やいくつかの記号については、メインレイヤーとは別のレイヤーに切り替えて入力する。
これまで使ってきたキーボードで最もキー数が少ないものでも Keyball61 の 61 キーとなっており、
基本的にメインレイヤーにすべての数字と記号を置くことができていた。
自分のメインで使うキーボード選定における条件の一つとして、
メインレイヤーでアルファベット、数字、記号を全て入力可能であることを含めていたため、
これまで leneko42C のようなキー数を使う機会がなかった。
しかし、メインのキーボードを探す旅としては、Keyball61 が当面の間の終着点だと思っているため、
経験として leneko42C を始めとし、Corne Cherry V3 のようなコンパクトなキーボードにも手を伸ばしてみている。

一先ずレイヤー 1 にデフォルトで設定されていたキーバインドは違和感があるので変更することで
数字や記号の入力を迷わずにできるようになった。
しかし、キーボードの右上に =\ (|)= が配置しているのに慣れない。
普段はこの位置に =- (_)= が配置されているのでここは逆にした方がいいかもしれない。
今あげたような細かい違和感はまだ存在するが 42 キーであってもプログラミングをするのではなく、
日本語の文章を書くだけであればそれほど困らないということがわかった。

つまり、普段日本語入力をメインに使っている人はフルサイズキーボードを使うのではなく、
42 キーのキーボードを使うのでいいのではないだろうか。
このサイズのキーボードはコンパクトで持ち歩くにもかなりいいように感じる。

不自由な点の二つ目はトラックパッドの挙動だ。
トラックパッドの精度自体は思っていたよりもよかったのでそこまでの不満はないのだが、
三本指のスワイプが Magic Trackpad のように macOS 側で設定した動作となってくれないのが結構なストレスとなる。
もしかしたらこれは設定を弄ることで解消できるかもしれない。
この点については、解決方法が見つかったら後日更新しようと思う。

もう一つトラックパッドの挙動で気になるのがドラッグ&ドロップの動作だ。
長押しか、押したときの強さでドラッグ状態への移行をを切り替えることができるのだがどちらの設定も違和感があり、
意図していないタイミングでレイヤーが切り替わってしまいイライラする。
これは設定値を弄ればいい感じの感度を見つけられる可能性があるのでもう少し試行錯誤してみる。

さて、上記の 2 点を除けば概ね満足できる買い物だったように思う。
しかし、[[https://kbd.arashike.com/corchim][Corchim]]を購入しているので、
こちらが届いたら普段遣いのコンパクトキーボードはそちらになるんじゃないかなーと思ってる。
Corchim が届くまでに leneko42C でコンパクトキーボードとレイヤーの活用を練習していきたい。

